AUX_SOURCE_DIRECTORY(. ALGORITHM_LIST)


source_group("${CMAKE_CURRENT_SOURCE_DIR}" FILES ${ALGORITHM_LIST} )

file(GLOB_RECURSE HEADER_FILES ${CMAKE_SOURCE_DIR}/include/algorithm/*.h)
ADD_LIBRARY(algorithm ${ALGORITHM_LIST} ${HEADER_FILES}) 


# 安装
INSTALL(TARGETS algorithm ARCHIVE DESTINATION lib)

# FILE(GLOB HEADER_FILE ./*.h ./*.hpp) #所有头文件存入变量
# FOREACH(F ${HEADER_FILE})
#     INSTALL(FILES ${F} DESTINATION ${PROJECT_BINARY_DIR}/install/include/algorithm)
# ENDFOREACH(F)







